### ISSUE TITLE
The step count will become negative after the phone is restarted

### ISSUE THREAD

**Issue by Changyun812** [doyou1/Pedometer#1]

**Comment by doyou1** [comment]
Thank you for pointing it out.
I thought I knew a little bit about step_counter, but I didn't know that it was reset when I rebooted.
Previously, there was an error where negative steps were stored, and I'm glad I found the cause.

First of all, I modified it with [the commit](https://github.com/doyou1/Pedometer/commit/8ad14e89485676d855bac541bf547d8691650ffe) here. (I forgot and didn't make a new branch.)
Although some logic has been created, it does not seem to be resolved the error in which negative steps are stored.
Therefore, if the current number of steps calculated temporarily is negative, it is blocked by not proceeding with DB update.
I think it's an error caused by launching the app before the bootReceiver starts, but we need to look at it more.

To explain the addition of temporary logic,

### when device reboot(I can't write "markdown" well. )
- // in BootReceiver.kt
- 1.if today item exist, set today item's initSteps = 0
- 2.1. save Reboot time
- 2.2. save Reboot hour's before steps

- // in DBHelper.kt process() 
- 3.check to reboot at today(reset step_counter to 0)
- 4.1. check that current hour is equal reboot hour or over reboot hour (don't mind reboot before data)
- 4.1.1. current hour == reboot hour
→targetSteps = reboot before steps + current steps
- 4.2.2. current hour > reboot hour
→targetSteps = current steps - reboot after steps(Logically, reboot after steps is initSteps)

This is the flow.
If you have any additional points to point out or advice on the direction of correction,
Thank you again for your good point.
